### ISSUE TITLE
Modal size different for specific social networks

### ISSUE THREAD

**Issue by Mte90** [Mte90/Share-Backported#10]
There are social that require a more bit modal

**Comment by Mte90** [comment]
We have to see how right now with scroll if the behaviour is better

**Comment by shgysk8zer0** [comment]
Are you planning to keep using `browser.windows.create` instead of changing the popup?

I've been trying to figure out how to load the share URL into the popup as the original ShareAPI used to work.

**Comment by Mte90** [comment]
That api is the only solution because from Firefox 57 open a popup is not working anymore.

**Comment by Mte90** [comment]
With #34 we can think of settings for every social to put a custom window size
