### ISSUE TITLE
Add "auto-save" in the option

### ISSUE THREAD

**Issue by Sav22999** [Mte90/Share-Backported#105]
It's very boring press every time "Save". Add the "auto-save" when an option changes or set the option "Auto-Save"-> if it's enabled, the "save" button is hidden and auto-save options, otherwise you need to press manually that button

**Comment by Ryuno-Ki** [comment]
I believe, we could generally need a way to flat the options as „dirty” to trigger the hide/show option.
Regarding automatically saving options: This should only be applied if we have an easy way to undo changes.
One way would be to apply [Redux](https://redux.js.org/) or [Flux](https://github.com/redux-utilities/flux-standard-action), but this could raise the complexity of this project.

Code-wise it's not much (I did implement my own code as part of js13kgames competition a couple of years ago).

**Comment by Sav22999** [comment]
Yeah, so it's better don't implement this feature...

**Comment by Mte90** [comment]
Yes, right now is too much for the number of settings and needs.
