### ISSUE TITLE
PageAction button is now invisible

### ISSUE THREAD

**Issue by Caspy7** [Mte90/Share-Backported#111]
Looks like with the Oct 18 update the PageAction button is now present, but invisible.

**Comment by Caspy7** [comment]
Tested on Nightly 71 and current release 69 in a fresh profile

**Comment by Sav22999** [comment]
@Caspy7 Are you using "dark theme", right?

**Comment by Mte90** [comment]
I saw this behaviour. Seems that in Firefox there are still issues with dark/light themes for pageaction.
I will check that ASAP.

**Comment by Caspy7** [comment]
FYI, I tested in a blank profile on Release, Firefox defaults to dark because of my system setting so I set the theme to light and installed and got the same results.

**Comment by Mte90** [comment]
My fault https://github.com/Mte90/Share-Backported/blob/a20819b822b2504bcaa72c035dac4fa1389dcc39/background.js#L48 here I didn't changed the filename

**Comment by Sav22999** [comment]
I'm working on it, to solve this bug 😄
