### ISSUE TITLE
If only one service is available, click on button should not show a menu

### ISSUE THREAD

**Issue by Geobert** [Mte90/Share-Backported#113]
I only use Twitter sharing feature so having the menu with only one service is kinda bothering.
It should immediatly trigger the sharing popup.

**Comment by Sav22999** [comment]
@Mte90 Can I work on this?

**Comment by Mte90** [comment]
Sure!

**Comment by Geobert** [comment]
Sorry for the very late feedback, but it seems it is broken at the moment 
![firefox_rzrze2knQP](https://github.com/user-attachments/assets/1fa7ff24-0357-4189-86c0-969d5897c094)

**Comment by Mte90** [comment]
Looking at the code there isn't anymore after 4 years so in the meantime we removed it.
Can you open a new ticket?
