### ISSUE TITLE
Feature request: keyboard shortcut

### ISSUE THREAD

**Issue by Geobert** [Mte90/Share-Backported#114]
It would be convenient to trigger the sharing through a hotkey combination :)

**Comment by Mte90** [comment]
This is not easy because we cannot inject a JS file in all the webpages.
We need to see if in the background of firefox it is possible and also to find an hotkey already used.

**Comment by Geobert** [comment]
I see, I was asking because I'm looking to replace Buffer extensions as I only share to Twitter anyway (and their addon configuration panel is broken). And they have a configurable shortcut. I don't know how it's done though.

If it's too hard, don't bother :)

**Comment by Mte90** [comment]
I don't think that is harder is mainly about what keys associate because we already have a `background.js`

**Comment by Ryuno-Ki** [comment]
Hm, what about adding [a command to `manifest.json`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands) like @cadeyrn did in https://github.com/cadeyrn/bookmarks-organizer/blob/62c8d517c6e0750aa08c31ed71834bac1aed2778/src/manifest.json#L22

**Comment by Ryuno-Ki** [comment]
@Geobert Which key would you like to use for sharing?

Further reading:
* [commands in manifest on MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands)
* [commands in JS on MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/commands)
* [commands in Chrome](https://developer.chrome.com/extensions/commands)

**Comment by Geobert** [comment]
When I posted this, I was thinking to mimic Buffer extension which has customizable field for the shortcut (Ctlr-B by default). 

But I don't use this Share-Backported  anymore so I won't complain :)

**Comment by Mte90** [comment]
We need to see what hotkeys are used by Firefox to find the one free.

I was thinking something like Ctrl+shift+1 it will be the first one in the modal and so on.

**Comment by Ryuno-Ki** [comment]
Firefox is binding to these keyboard shortcuts: https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly

However, there are OS-related ones, too.

Buffer has the advantage, that <kbd>B</kbd> is normally unused. <kbd>S</kbd> is a different beast …

**Comment by Ryuno-Ki** [comment]
What do you think about binding the share modal to <kbd>y</kbd>?

I think, it isn't used that widely (I'm only aware of it being „Redo” in some applications), but it resembles the [share icon](https://en.wikipedia.org/wiki/Share_icon#/media/File:Sharethis.svg) in a way.

**Comment by Mte90** [comment]
I already have some experience with hotkeys of an extension (with my other extension), we need to exclude hotkeys used by the webpage but also firefox.
So using ctrl+shift helps us to avoid conflicts and adding a number helps to pick the first/second/third one on the modal etc.

**Comment by Mte90** [comment]
So we have an hotkey to open the share modal, wondering if it is enough.

**Comment by Ryuno-Ki** [comment]
If you ask me: ship it.
Then listen to feedback.

For example, the next best thing I could imagine is navigating with arrow keys through the share options.
But that would increase the complexity.
As long as I'm the only one, I wouldn't do it.

**Comment by Ryuno-Ki** [comment]
You can open the modal using <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>y</kbd> now. Closing this issue.
