### ISSUE TITLE
Add new services

### ISSUE THREAD

**Issue by Sav22999** [Mte90/Share-Backported#118]
Add new services:
- WeChat
- Facebook Messanger
- Mail.ru
- Yammer

**Comment by Sav22999** [comment]
If you agree, I can work on it 😄

**Comment by Ryuno-Ki** [comment]
Since I don't use those, go for it! (Was it done in #118?).
If already complete, what's stopping this ticket from being closed?

**Comment by Sav22999** [comment]
I don't have implement every service in that list... actually I tried but I think Yammer, WeChat, Facebook Messenger and Mail.ru can't be implemented ...

**Comment by Mte90** [comment]
I think that instead to add any service that we found is better to wait for requests and add the most used services like it is now.
In this way we don't add any service that won't be used.
I think to close this one and work on https://github.com/Mte90/Share-Backported/issues/107

**Comment by Sav22999** [comment]
Oh, I asked them becauso Facebook Messege is used also in Italy, WeChat is used is part of Asia, Kakao in used i (Korea South), Mail.ru is used in Russia, LINE is used in Japan (I think), ect. It was just to became the addons more "international".
