### ISSUE TITLE
Add option to change the columns number of services

### ISSUE THREAD

**Issue by Sav22999** [Mte90/Share-Backported#119]
Now it's "dynamic" just the height (row). It would be very nice can choose columns number of services (now it is 4, and you cannot change it).

It is, I think, enough easy because the width is set on "modal.js"

**Comment by Tessituraa** [comment]
Can I work on this?

**Comment by Ryuno-Ki** [comment]
After the merge of #137 this should be re-evaluated.

**Comment by Mte90** [comment]
Indeed, with small are 4, medium 3 and large 2.
