### ISSUE TITLE
Bring back sharing to diaspora*

### ISSUE THREAD

**Issue by arnaud-jacquemin** [Mte90/Share-Backported#12]
Hello
Diaspora* was available with the old share button : https://activations.cdn.mozilla.net/en-US/diaspora.html
It should be backported too!
I can contribute a patch if you are interested

**Comment by Mte90** [comment]
The issue of diaspora is that need a configuration for enable the share to the specific domain like for mastodon.
And extension doesn't contain anything for it, we can add something in the option but probably the best way is to add a new window opened when you click to share to mastodon/diaspora that ask where share and with a list that remember the previous used.
Actually I don't use mastodon neither diaspora so if you want to contribute we can start to discuss on the best way to implement that :-)

**Comment by arnaud-jacquemin** [comment]
There is an official "multi-instance" share URL at https://share.diasporafoundation.org/about.html.
That's the trick used by Mozilla's current share service (as of Firefox 55).
The ability to setup custom domains directly in the extension would be great... but I would target feature parity first, maybe new features later ;)
