### ISSUE TITLE
Set background of options.html dark/light, based on theme color

### ISSUE THREAD

**Issue by Sav22999** [Mte90/Share-Backported#121]
Now Firefox implemented theme also in about:addons, so the background of options is white (instead of dark/black)

![immagine](https://user-images.githubusercontent.com/32335378/67345249-afed8d00-f53a-11e9-863f-2ab8a17f80c6.png)

**Comment by t-matsuu** [comment]
Icon in the URL bar is not clear with dark theme.
![icon in dark theme](https://user-images.githubusercontent.com/21326714/72657962-25f47980-39ee-11ea-8bd4-51b4f98ce7cb.png)

**Comment by Sav22999** [comment]
@t-matsuu This is because in Firefox there isn't a way to know where is the main colour of icons, so we just control if it's "Light" (defaut theme, in RGBa code), or "Dark"(dafault theme). In addition, I advise you to open a new issue, because this bug is different to the first one
