### ISSUE TITLE
Sharing services is not the same selected services in options

### ISSUE THREAD

**Issue by zefilipe** [Mte90/Share-Backported#122]
Good morning,

Today, i want share an article, and the services available in dialog modal, are different that active services  selected in the options !

Regards.

**Comment by Mte90** [comment]
There was an issue with a previous version, what version are you using?

**Comment by zefilipe** [comment]
I'm using version 2.0.4

**Comment by Mte90** [comment]
version 2.0.1 fixed the issue, can you try to save again the settings?

**Comment by zefilipe** [comment]
i do this but the bug persists !

**Comment by Mte90** [comment]
Can you go to the settings and save the options?

**Comment by zefilipe** [comment]
yes i saved but dont has any effect !

**Comment by Mte90** [comment]
Did you tried to remove and install again? I cannot replicate that issue.

**Comment by Ryuno-Ki** [comment]
If you struggle with that, perhaps you could record your desktop and share a video?

**Comment by zefilipe** [comment]
> Did you tried to remove and install again? I cannot replicate that issue.

I tried to remove and install again, checked options to hide, and again works ;-)

Thanks you !
Regards
