### ISSUE TITLE
Auto close the window for Reddit

### ISSUE THREAD

**Issue by Mte90** [Mte90/Share-Backported#125]
Right now we are doing this for FB, TW and Linkedin because it is easy (the url changes) so we can do also that for Reddit.

**Comment by whitemalt** [comment]
Hi, Can you share, how to set up project?

**Comment by Mte90** [comment]
You can check at https://extensionworkshop.com/

**Comment by whitemalt** [comment]
> Right now we are doing this for FB, TW and Linkedin because it is easy (the url changes) so we can do also that for Reddit.

Can you share commit which you are doing on your code FB , Twitter, I need more information about this story ^^

**Comment by Mte90** [comment]
This is the line https://github.com/Mte90/Share-Backported/blob/master/background.js#L24
As I can see the reddit support is here but is not working anymore.

Basically the extension open a window and with a browser method if the url changes we do a check if the final page of a service, to avoid redirects and this kind of things.

**Comment by Ryuno-Ki** [comment]
(@Mte90 If you hit <kbd>y</kbd> on a code page, GitHub will update the URL to a canonical/stable one. As an added bonus, we would see the referenced code here.
More goodies behind <kbd>?</kbd>)

**Comment by Ryuno-Ki** [comment]
#158 is getting us 80% there.

https://github.com/Mte90/Share-Backported/blob/3f38d4f4d31dff3b998bf33fd5f1631767170948/background.js#L41-L44
needs an update with the part of the URL, that indicates a successful share.
Therefore, inspect from about:debugging the modalUrl from

https://github.com/Mte90/Share-Backported/blob/3f38d4f4d31dff3b998bf33fd5f1631767170948/background.js#L47

**Comment by Mte90** [comment]
I did some testing, Reddit on selecting the sub to share change the url and again after posting with urls like this:

* https://reddit.com/submit?url=https%3A%2F%2Fwww.google.com%2F&title=Google
* https://www.reddit.com/user/Mte90/submit?url=https%3A%2F%2Fwww.google.com%2F&title=Google
* https://www.reddit.com/user/Mte90/comments/jdzh7f/google/

So I merged the new code but I think that we need regex support to be able to detect urls like: `https://www.reddit.com/*/*/comments/*/*` with `*` I mean everything there.

**Comment by Ryuno-Ki** [comment]
Instead of RegExp (see https://xkcd.com/1171/ ), can it be defined as pair of `hostname` and `path` contains `comments` (or another keyword)?

**Comment by Mte90** [comment]
Well if contain comments can be fake positives detection, for that reason I would prefer a regex.

**Comment by Ryuno-Ki** [comment]
Hm, what about split on `/` and check for third position?
I'm really trying to avoid RegEx if possible.

**Comment by Mte90** [comment]
Well if we do in that way is more easy with a regex, we can have other services that use other symbols.

**Comment by Ryuno-Ki** [comment]
:shrug: Do as you please.
