### ISSUE TITLE
Add option to choose the size of buttons

### ISSUE THREAD

**Issue by Sav22999** [Mte90/Share-Backported#126]
I think it's a good idea can choose the size of buttons (not just one, but everyone) in the pop-up menu. Maybe some fixed sizes: "50x50", "100x100", "150x150".

**Comment by Mte90** [comment]
I think that if we have all svg image files is not a problem.

**Comment by Sav22999** [comment]
@Mte90 yes, but actually it's not necessary. I mean, if an image (png) is 300x300, you don't lose quality of that one is you reduce the size (you can set the image size: `background-size: 100px 100px` (or, if i'ts an img: `width: 100px; height:100px`)) so it's not impossible 😄
