### ISSUE TITLE
Extension stopped working on Firefox 74 beta

### ISSUE THREAD

**Issue by teohhanhui** [Mte90/Share-Backported#127]
There's no page action present in the location bar. In the `...` menu, there's a Share Backported menu item, but it's greyed out and does nothing.

**Comment by Mte90** [comment]
Did you tried on pressing the button?
Because I am using it on Nightly without any problems. 
Can you open the settings and changing them and save them?

**Comment by teohhanhui** [comment]
Toggling settings and saving did not seem to fix the problem, but the page action has come back after toggling "Run in Private Windows".

**Comment by Mte90** [comment]
So if you click on the extension icon, you get a blank window. The only reason is that there aren't any social configured or there is an error.
Considering that you are the only user with that problem I think that is something now working with your settings.

**Comment by teohhanhui** [comment]
> So if you click on the extension icon, you get a blank window.

No, actually, what happened was the the page action disappeared, and the menu item in the overflow (...) menu read "Share Backported" (instead of "Share") and was disabled. So the extension was kind of disabled?

**Comment by Mte90** [comment]
The pageaction can be disabled/enabled in the settings, did you checked if it is enabled?

**Comment by teohhanhui** [comment]
Yes, it was never disabled. But toggling that didn't help either (it's what I toggled when you suggested changing the settings and saving).

**Comment by Mte90** [comment]
I think that another test you can do it is remove and install again the extension.

**Comment by teohhanhui** [comment]
I suspect this has to be a Firefox bug. Because as I've previously mentioned, toggling "Run in Private Windows" fixed it for me.

Now I tried removing and reinstalling the extension, and was able to get the extension to stop working by toggling "Run in Private Windows", and wasn't able to get it to work again other than to reinstall again. I could not reproduce on the subsequent reinstall.

**Comment by Gae-IT** [comment]
I've the same problem, partially get working with share backported button on the right of the address bar

![sharebackp_1](https://user-images.githubusercontent.com/64748300/80922438-77e2c480-8d7d-11ea-9b1d-b89e42fce45c.png)

and in firefox settings I noticed the following

![sharebackp_2](https://user-images.githubusercontent.com/64748300/80922450-7e713c00-8d7d-11ea-9877-977325d41b0b.png)

**Comment by Mte90** [comment]
So trying to understand the icon in the address bar was disappeared and the one in the page action list is not working?

About the other warning, I saw it too but is because the extension supports also firefox containers, (in italian "schede contenitore").

**Comment by Gae-IT** [comment]
the icon in the address bar, near the search, is grayed but if I click it works and share the link.
the one in the page action list (showed when click 3 dots in the address bar) is grayed, not clickable and doesn't works.
same problem on another PC I've
maybe it conflict with others addons..eg. ublock origin?

**Comment by Mte90** [comment]
Did you disabled the page actions? there is an option in the settings and about the icon it is a bug in firefox where we don't have an api to understand the firefox theme to use the right icon color.

**Comment by Gae-IT** [comment]
I tried disabled page actions, don't solve the issue. also enabled don't solve it.
the button works as expected, the color does not matter at the end.

I understand you can't fix it if you'aren't able to reproduce...  how I can help?

**Comment by Mte90** [comment]
I don't know if it is a firefox issue or of the extension. The only way is to disable and renable the extension or test it with another firefox profile.

**Comment by Gae-IT** [comment]
I've tested enable/disable the extension, without success.

looking at the firefox console I notice the following:

![sharebackp_3](https://user-images.githubusercontent.com/64748300/80977212-b2536c80-8e24-11ea-9177-3688bf8b7dbb.png)

looking at extension console there is an error:
TypeError: themeInfo.colors.toolbar_field is null    ... background.js:50:9

then I tested also with a new profile, but looking at extension console I notice the following:

![sharebackp_4](https://user-images.githubusercontent.com/64748300/80977265-c8612d00-8e24-11ea-94c5-23315004374d.png)

I'm sorry I don't think I can do more

**Comment by Mte90** [comment]
Uhm I think that you spotted a bug in the extension I will investigate :-D

**Comment by Mte90** [comment]
There is a new version that fix that error, seems that some theme have some issues with the new api and we wasn't doing carefully all the checks.

**Comment by Gae-IT** [comment]
well done, thanks

just this morning I used another old pc with updated firefox 75 and share backported 1.0.12 and it works fine, I also noticed the share backported pageaction icon is darker in version 1.012 and look better

ciao
