### ISSUE TITLE
Add Friendica support

### ISSUE THREAD

**Issue by SpencerDub** [Mte90/Share-Backported#128]
Friendica appears to have a bookmarklet functionality that could be used in this extension. A URL for sharing a page looks like this:

`https://example.com/bookmarklet?url=http%3A%2F%2Fweb.mit.edu%2F&title=MIT - Massachusetts Institute of Technology&jump-doclose`

(That's what you get when trying to share [this page](http://web.mit.edu/).)

Could support for Friendica sharing be added, please?

**Comment by Ryuno-Ki** [comment]
FWIW the source code is https://github.com/friendica/friendica/blob/master/mods/bookmarklet-share2friendica/bookmarklet-share2friendica.js

Where would you enter the Friendica hostname? (I haven't the Add On on this machine)

**Comment by Mte90** [comment]
We can add a field for the hostname like for shaarli.
