### ISSUE TITLE
If it shown "You can share this tab" the height doesn't change

### ISSUE THREAD

**Issue by Sav22999** [Mte90/Share-Backported#141]
![image](https://user-images.githubusercontent.com/32335378/95654328-a66c8480-0aff-11eb-9a50-54ca0bc77048.png)

The row should be set at "1" (or 2)

In addition, I think it's better say "You can share this link" (instead of "tab")

**Comment by Ryuno-Ki** [comment]
I disagree.

For one, #137 will reduce the height (since it switches to a `min-height` in CSS).

Second, the Web Extension is using the currently open tab for sharing. A „link” could be a highlighted piece of content (or an option for the context menu), which isn't part of this extension (to my knowledge).

**Comment by Sav22999** [comment]
But "tab" mean you cannot share other website/link in that specific tab

**Comment by Ryuno-Ki** [comment]
Which is the actual behaviour as far as I know.

@Mte90 Halp!
I don't get what Sav is asking for here :-(

**Comment by Sav22999** [comment]
@Ryuno-Ki No, the behaviour you want to is to avoid the URL "about:" etc. not the entire tab. The tab remains the same if you go, after, to "facebook.com", for example, but then you can share that specific URL/link.

I don't know how can I explain it in other ways, actually.

**Comment by Mte90** [comment]
As I understood is mainly a wording issues, as we are not sharing the tab but the link of the tab.

**Comment by Ryuno-Ki** [comment]
What term is better understood by users?
I mean, okay, you can navigate within one tab to another URL.
But even then, you're sharing the link of the current *tab*.

Either way, I leave the decision to you, @Mte90.

**Comment by Sav22999** [comment]
@Ryuno-Ki in fact "[...] **this link**", you need to specify that the link you can't share is "this" (so of this tab, it is implicit)

**Comment by Mte90** [comment]
I am to change the wording with `link`.

**Comment by Mte90** [comment]
Anyway the latest pr fix the height we need just a fix to the wording that I will do now, so I can release a new version.
