### ISSUE TITLE
Change also the colour of textboxes and buttons

### ISSUE THREAD

**Issue by Sav22999** [Mte90/Share-Backported#142]
![image](https://user-images.githubusercontent.com/32335378/95654378-dae04080-0aff-11eb-9bc8-97a9446984c5.png)

**Comment by Ryuno-Ki** [comment]
What would you expect?

To me, those are quite readable already.
A blank input is an affordance, that the user is meant to enter something.

**Comment by Sav22999** [comment]
@Ryuno-Ki Black

**Comment by Ryuno-Ki** [comment]
Dark grey on black is hardly readable …

**Comment by Sav22999** [comment]
@Ryuno-Ki Nope. Please, see also Mozilla graphics.

The textboxes aren't white, they are black instead! Same of buttons

**Comment by Ryuno-Ki** [comment]
Now, we are talking!

So this issue is about to adopt the colour scheme Mozilla is using in their `about:` pages!

**Comment by Sav22999** [comment]
@Ryuno-Ki It was just an example. In the dark themes you need to change also textboxes, and usually they are black.

We already use the Mozilla colour scheme (see the light-blue box-shadow, which is used by Mozilla)
