### ISSUE TITLE
Dark theme: icons issues

### ISSUE THREAD

**Issue by Sav22999** [Mte90/Share-Backported#143]
![image](https://user-images.githubusercontent.com/32335378/95654397-fea38680-0aff-11eb-80e8-bb6d072b0bf9.png)

For the dark theme I would add a shadow for icons, because some of them aren't visible (tumblr, archive)

**Comment by Ryuno-Ki** [comment]
Instead, I'd suggest to swap the icons with some, that are legible on light and dark theme.

**Comment by Sav22999** [comment]
@Ryuno-Ki Yes, it's good too

**Comment by GrosBourrin** [comment]
background of icons should be transparent, some icons as twitter have some grey in bkg, i have a css theme that reveals that "issue"
![2020-12-05_05h17_33](https://user-images.githubusercontent.com/40931468/101233609-5520e180-36b9-11eb-963e-8fe4f18c679b.png)

**Comment by Mte90** [comment]
I see that issue also with a light theme. It is with some icons so maybe there are some conflicts with those files.

**Comment by Mte90** [comment]
it is time that I look on that issue.

**Comment by Sav22999** [comment]
@Mte90 I'm too busy with exams in these weeks, sorry. Maybe @Ryuno-Ki can fix this
