### ISSUE TITLE
Add "title" (hover) to img in modal

### ISSUE THREAD

**Issue by Sav22999** [Mte90/Share-Backported#144]
I would like know the service, so add the "title" attribute

**Comment by Mte90** [comment]
On the img tag and not in the button as #156

**Comment by Ryuno-Ki** [comment]
To be more specific: On the `<img />` tag as `alt` attributes.

**Comment by Sav22999** [comment]
@Ryuno-Ki `alt` is the `alternative`, it's not the (tooltip) `title`

**Comment by Mte90** [comment]
We know but someone did a pr to the wrong html tag.

**Comment by Ryuno-Ki** [comment]
I'm aware of that. However, Firefox <del>is showing</del> used to show it as a tooltip, too! Looks like you'll need to add a `title` attribute there nowadays. Be aware that it [has UX drawbacks](https://developer.paciellogroup.com/blog/2012/01/html5-accessibility-chops-title-attribute-use-and-abuse/). I'd suggest to use both until we came around to implement a [proper tooltip](https://inclusive-components.design/tooltips-toggletips/). 

![Share-Backported](https://addons.cdn.mozilla.net/user-media/addon_icons/850/850331-64.png?modified=1601558335 "Share Backported")

I was referring to https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/alt#Images_used_as_buttons
