### ISSUE TITLE
If there aren't services it doesn't work

### ISSUE THREAD

**Issue by Sav22999** [Mte90/Share-Backported#145]
It should show a message error, instead of anything

**Comment by Ryuno-Ki** [comment]
It doesn't?

For me, I can see an error message in the modal.
Can you share a screenshot?

**Comment by Sav22999** [comment]
![image](https://user-images.githubusercontent.com/32335378/95663806-6da1cf00-0b42-11eb-9cdc-fcb973d75aa0.png)
 You see it wants to show you something, but there aren't elements, so it doesn't show anything

**Comment by Ryuno-Ki** [comment]
m(

I found the issue. Bugfix is coming …
