### ISSUE TITLE
Pageaction Icon is black, should be grey

### ISSUE THREAD

**Issue by pwd-github** [Mte90/Share-Backported#15]
It's currently way darker than everything else on Firefox 57 and that makes it quite distracting.

**Comment by Mte90** [comment]
actually pageaction doesn't support themed icon but I am following the ticket

**Comment by shgysk8zer0** [comment]
Let me know when you figure this one out. `pageAction` seems to have no theme support or support for `fill="context-fill"` in SVG icons.

You can see some example icons and see default colors at [Firefox Icons](http://design.firefox.com/icons/viewer/).

**Comment by Mte90** [comment]
I opened the ticket on the first implementation of pageaction on this extension: https://bugzilla.mozilla.org/show_bug.cgi?id=1397196

**Comment by past** [comment]
Have you tried setting fill-opacity="context-fill-opacity" in the SVG? This might do the trick per: https://bugzilla.mozilla.org/show_bug.cgi?id=1395387#c11

**Comment by Mte90** [comment]
Actually for pageaction there is not support for themes also if the icon for the light is already available in that extension.

**Comment by clivend** [comment]
sorry for dumb question but I dont want to open an issue just for that :)
I was just asking myself what's pageaction anyway??
thanks!

**Comment by teohhanhui** [comment]
@clivend https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/pageAction

**Comment by Mte90** [comment]
Seems that now on Firefox 58 this problem doesn't happen anymore

**Comment by pwd-github** [comment]
I'm still seeing this issue on Nightly.

![sharepageactionistheonlyblackone](https://user-images.githubusercontent.com/203217/33125502-97ba5e1e-cf78-11e7-8487-dc72da24bb5d.png)

**Comment by Mte90** [comment]
Very strange on FF 58 I don't have that problem, the color icon is changed on toolbar but not the page action

**Comment by freaktechnik** [comment]
@shgysk8zer0 it only returns values when the theme was modified by an extension. The built in dark/light themes don't count as that, apparently.

**Comment by nt1m** [comment]
@freaktechnik @shgysk8zer0  Yeah, unfortunately, built-in light/dark themes are not WebExtension themes yet.

**Comment by freaktechnik** [comment]
@nt1m neither does the standard theme with colors modified by the GTK theme.

**Comment by nt1m** [comment]
@freaktechnik A workaround you can use is making a WebExtensions theme with system colors (any css color works, so you can use -moz-Dialog/-moz-Field/...)

**Comment by Mte90** [comment]
I tested now the 1.2.0 on Firefox 60 and the icon change based on the theme, check for an update inside your firefox in the next hours for it :-D

**Comment by freaktechnik** [comment]
I think @pwd-github uses a dark GTK theme and not a dark Firefox theme and that is still not recognized.

**Comment by nt1m** [comment]
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1441708

**Comment by pwd-github** [comment]
As @freaktechnik said... Here's a screenshot of the issue still existing
![screenshot from 2018-04-23 14-05-06](https://user-images.githubusercontent.com/203217/39128416-a18fa1ac-46ff-11e8-9c57-c641d5b3552f.png)

**Comment by pwd-github** [comment]
And just to further drive home the issue, here's the issue on a light theme
![screenshot from 2018-04-23 14-08-49](https://user-images.githubusercontent.com/203217/39128541-f3a74a26-46ff-11e8-8d72-1fb8ef110567.png)

**Comment by freaktechnik** [comment]
that bug nt1m linked only applies to the toolbar button, not the page action button, btw. I think the issue is only addressed for the toolbar button in general.

**Comment by pwd-github** [comment]
@Mte90 You've kept this issue closed despite it not being fixed.

**Comment by freaktechnik** [comment]
@Mte90 you have both a page and a browser action, how do you switch the page action icon based on the theme?

**Comment by Mte90** [comment]
Doh I misconfused `page_action` with `browser_action`. The second has the support for dark themes but not the first one.

Actually there is no way to detect the theme by code, I am right?

**Comment by rugk** [comment]
Oh icon problems. I also had these, and here are some resources to go:
* Here are the colors you have to use, you have to hardcode them: https://design.firefox.com/photon/visuals/color.html#icons-and-other-elements
* Here is how to properly support themes for _browser_actions_! https://discourse.mozilla.org/t/how-to-correctly-design-color-icon-to-be-visible-across-themes/27713
* Supporting themed page actions, is even harder: https://discourse.mozilla.org/t/use-theme-colors-for-svg-favicons/29165

Easiest solution may be to just offer the user a switch (for the page action), where you switch between these two favicons.

**Comment by Mte90** [comment]
If you see my previous comment for `browser_actions` is already supported.
The problem is with `page_action` because there is no api to know if the theme in use is light or dark and the only way is add an option and I don't like so much that solution.

**Comment by shgysk8zer0** [comment]
It real irritates me that Mozilla still doesn't offer this.

I wish they'd just use inline SVG for icons, set `color` somewhere, and let us use `fill=currentColor` (not sure if that works as an attribute, but it's available in CSS).

Considering how long it's been, I kinda want to protest the lack of solution (at least available to us) by getting a bunch of developers to make all icons lime green.

**Comment by Mte90** [comment]
An year is gone but the problem still exist, there is a ticket about it https://bugzilla.mozilla.org/show_bug.cgi?id=1409107

**Comment by Sav22999** [comment]
I'm working on it 😄

**Comment by Mte90** [comment]
I am releasing a new version with a code that check the colors for the default Firefox themes and automatically switch the icon.
