### ISSUE TITLE
Run linting on pull requests

### ISSUE THREAD

**Issue by lmillucci** [Mte90/Share-Backported#153]
I think we should add linting for each pull requests. We can implement this using [GitHub Actions](https://github.com/features/actions) that is free for open source projects

**Comment by Mte90** [comment]
I agree or we can integrate a service like Codacy.
To me it's the same :-D

**Comment by Ryuno-Ki** [comment]
:popcorn: 

Which linter?
ESLint?
Prettier?
Standard.js?

**Comment by lmillucci** [comment]
> I agree or we can integrate a service like Codacy.
> To me it's the same :-D

I'dont know any of them so I'don't have any preference. This is a chance to try one of them for me. If you have preference let me know :)

> Which linter?
We already have eslint

**Comment by Mte90** [comment]
I am for eslint as we have packages.json configured for that.
Also @lmillucci don't forget to ad your name to the readme as you already did some pull requests.

**Comment by Mte90** [comment]
Codacy is already enabled to this repo but not on pull requests, I am doing it now
