### ISSUE TITLE
Please consider adding a dictionary lookup share

### ISSUE THREAD

**Issue by gunnora** [Mte90/Share-Backported#161]
From time to time, I'd like to look up the meaning of a word I encounter while reading online. I'd love to be able to highlight a word, then use Share-Backported to go look it up in the Merriam-Webster dictionary or some such.

If I wanted to look up the word "share" in the M-W Dictionary, the URL would look like this: https://www.merriam-webster.com/dictionary/share

Is it possible for Share-Backported to pick up a highlighted term, tack it to the end of the string "https://www.merriam-webster.com/dictionary/", then go to the new URL that is created?

Another nice feature would be to be able to highlight a word or phrase and use Share-Backported to send it for a Google search. To look up "Share Backported", the URL would be https://www.google.com/search?q=share+backported

**Comment by Mte90** [comment]
Hi Gunnora, this will require a new functionality and adding the support for the extension to inject a javascript in all the pages with all the issues that can create.
Also creating support for right click menu and other things.

I see that there are already a lot of extensions for that dictionary that support selection https://addons.mozilla.org/firefox/search/?platform=linux&q=webster

So I think that is something that we can avoid implementing as there are already alternatives.

**Comment by gunnora** [comment]
Thanks for the pointer to the M-W addons!
