### ISSUE TITLE
Ugly display

### ISSUE THREAD

**Issue by alexisju** [Mte90/Share-Backported#162]
Hi, I don't understand why the plugin is displayed like that:

![ugly share](https://user-images.githubusercontent.com/3707029/104160796-040bb800-53f2-11eb-9563-42a04e4cf1b2.png)

- Icons are configured "small" but seems not really "small". 
- First one still big in particular.
- On hover, the are a big ugly frame around the icons (when browser use dark mode) (twitter is hovered in the screenshot).

Whats happen, why it is not clean ? 
(before complaining, i have removed the plugin, cleaned the browser cache et and reinstalled the plugin. But not change).

**Comment by Mte90** [comment]
@Sav22999 there is something with the reset.css we are using.
As example I don't have that issue but I guess that is part of #143

**Comment by alexisju** [comment]
There is something i can do to fix this manually in the .mozilla/firefox directory ?

**Comment by Mte90** [comment]
No it is something that we need to do on our side.
Youn can see that on #143 there is the same issue you have.
