### ISSUE TITLE
Facebook issue sharing to contacts in messenger

### ISSUE THREAD

**Issue by GrosBourrin** [Mte90/Share-Backported#164]
Hi, i love your webext but i report an issue .
When sharing a webpage link to a contact in facebook messenger it says it can't find the  attachment !
Sorry it's in french but it's the same. i unistalled the extension, reinstalled it but it's the same issue .

![image](https://user-images.githubusercontent.com/40931468/104406663-1a378680-5560-11eb-95de-c52c9d1a913c.png)

**Comment by Mte90** [comment]
Reinstall doesn't fix the issue.
The web extension doesn't support facebook messenger but just facebook so I don't understand the issue.

**Comment by GrosBourrin** [comment]
oh ok i understand now, thanks for reply then

**Comment by Ryuno-Ki** [comment]
Can we close this?

**Comment by GrosBourrin** [comment]
> 
> 
> Can we close this?

oh sure :)
