### ISSUE TITLE
'browser' is not defined

### ISSUE THREAD

**Issue by Mte90** [Mte90/Share-Backported#17]
Add the rules for jshint to avoid that error

**Comment by ghosh** [comment]
I can pick this up. Where do you want to add the rules? Are you talking about a comment to ignore the during linting? Or would you rather have a separate jshintrc file?

**Comment by Mte90** [comment]
Probably is better a jshintrc file, there are different js files on this project :-)

**Comment by ghosh** [comment]
ok thanks. I'll pick this up this weekend. A question though - where is the linting taking place? Is it in the code editor or via some external script somewhere?

**Comment by Mte90** [comment]
Actually in my editor, I a not using a task runner for the development so the file will be enough for everyone :-)
