### ISSUE TITLE
First icon is bigger

### ISSUE THREAD

**Issue by Mte90** [Mte90/Share-Backported#171]
If you change the icon size from the settings the first icon is bigger like doesn't get the changes.

**Comment by Manas146** [comment]
I would like to work on this issue.

**Comment by Mte90** [comment]
The ticket is yours, otherwise I was starting to debugging today 😂

**Comment by dag7dev** [comment]
To be more clear:
![image](https://user-images.githubusercontent.com/44711271/135923406-12ba96b8-71b1-455b-902f-609df89e2797.png)
If you set this and open the extension, the first icon will be displayed as bigger than the other ones.
