### ISSUE TITLE
URL share button disappeared after the last update.

### ISSUE THREAD

**Issue by Caspy7** [Mte90/Share-Backported#174]
I noticed the share button disappeared from inside the URL bar after the last update (2.1.3).

I installed the prior version (2.1.2) and it reappeared. Installed the most recent again and it disappeared.

**Comment by Caspy7** [comment]
Oops. Should have mentioned I'm on Nightly, 95.0a1 (2021-10-19) (64-bit)

**Comment by Mte90** [comment]
Hi, I already replied on https://github.com/Mte90/Share-Backported/issues/173

Firefox removed the pageaction support so I removed that code.

PS: I am on nightly too and I don't see them since months
