### ISSUE TITLE
Firefox Container support

### ISSUE THREAD

**Issue by Mte90** [Mte90/Share-Backported#2]
The api is https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contextualIdentities

The best way is to check if there are contextual identities on opening the modal and load that on the tab opened for the share

**Comment by stripTM** [comment]
I have a question. This issue will allow you to manage if it is visible or included in url-bar within the new icon [...] "Actions with the page", in this icon are located "Copy Link","Send Link"...?
![barra_direcciones](https://user-images.githubusercontent.com/1289297/30435873-24305838-996b-11e7-89a8-a6e2efea6e58.png)
![barra_direcciones_abierta](https://user-images.githubusercontent.com/1289297/30435958-5d7773e2-996b-11e7-9db1-f9ceb1d5b70e.png)

**Comment by Mte90** [comment]
No this is another issue :-) PS: (the next version will have an option to hide the pageaction of this extension)

**Comment by Mte90** [comment]
The new release will have the Container support
