### ISSUE TITLE
Hide pageAction button in edit mode

### ISSUE THREAD

**Issue by teohhanhui** [Mte90/Share-Backported#20]
The default "Save to Pocket" and "Bookmark this page" buttons are hidden when editing text in the location/search bar, but the "Share" button is not.

**Comment by Mte90** [comment]
Can you give more info about that?
I use the pageaction icon and I have the bookmark this page icon.
Can you explain better what do you do with screenshots?

**Comment by teohhanhui** [comment]
Normal mode:
![normal mode](https://user-images.githubusercontent.com/548843/31116007-0e688c1e-a857-11e7-871a-8c18fe7b3571.png)

Edit mode:
![edit mode](https://user-images.githubusercontent.com/548843/31116012-11b115ee-a857-11e7-9f9f-2b72624b4507.png)

The "Share" button should be hidden in edit mode.

**Comment by Mte90** [comment]
Very strange because on my Firefox this doesn't happen.
What firefox version are you using?

**Comment by teohhanhui** [comment]
Firefox 57.0b4
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0
OS: Linux 4.10.0-35-generic

**Comment by Mte90** [comment]
Actually there is no API to detect when the address bar is on the edit mode so fro me is impossible to hide the icon :-/
