### ISSUE TITLE
Add menu item in pageAction overflow dropdown

### ISSUE THREAD

**Issue by teohhanhui** [Mte90/Share-Backported#21]
It'd be great to have a "Share Link..." menu item in the overflow dropdown.

**Comment by Mte90** [comment]
There is already in the pageaction menu of Firefox share link by email or to a device.
Can you explain better what do you need?

**Comment by teohhanhui** [comment]
What I mean is for this add-on to add its own menu item to the pageAction menu. Is that possible?

**Comment by Mte90** [comment]
Uhm I am not sure I have to check the api

**Comment by Mte90** [comment]
The api enable only to add new icons but not for the the dropdown menu.
Actually there is an option to remove the icon as pageaction and use the button of the extension itself.
