### ISSUE TITLE
Ability to share with the default' mailto:' target

### ISSUE THREAD

**Issue by klint** [Mte90/Share-Backported#22]
Hi
Would it be possible add a share target that would be the local email client?
It could be useful at work, to share a page over work email (often via local email client), or over personal email (often Gmail or so).
Thanks

**Comment by Mte90** [comment]
Is not possible without using native messaging and implement that for every operative systems and for every email client, so quite impossible :-/
The best way is to copy (there is a button as pageaction in the dropdown for it) and paste in the email.

**Comment by klint** [comment]
I'm not really a developer, but isn't there a way by building and opening a kind of "mailto:" hyperlink which would trigger the native mail client whatever the OS is?  just asking :).
Thanks

**Comment by Mte90** [comment]
Uhm depends on the configuration of the browser as example in my browser automatically open gmail.
I am not sure of this behaviour will work with clients by an extension if it is possible to execute this kind of links.

**Comment by klint** [comment]
I got it. Then I'm ready to change my request to "ability to share with  the default' mailto:' target" 😉

**Comment by klint** [comment]
Hi
I just have discovered that this feature is now built-in in Firefox 57, available from the "..." within the address bar. Which makes my request redudant with it. Thanks

**Comment by Mte90** [comment]
No problem :-)
