### ISSUE TITLE
Add Mastadon support

### ISSUE THREAD

**Issue by semente** [Mte90/Share-Backported#23]
https://mastodon.social/about

Thank you very much!

**Comment by Mte90** [comment]
Already asked on https://github.com/Mte90/Share-Backported/issues/3

**Comment by sknebel** [comment]
#3 was closed without Mastodon support actually being implemented. Does that mean you consider Mastodon support "wontfix"?

**Comment by Mte90** [comment]
Actually as explained on https://github.com/Mte90/Share-Backported/issues/3#issuecomment-326934535 there is this problem that actually Mastodon doesn't cover. The extension is pretty simple open a link outside with the share dialog box and for mastodon doesn't exist that can cover all the website like exist already for Diaspora.
So it is not "wontfix" but more "actuallytherearenoway" for do it (at least without someone came here with a new idea!).

**Comment by stragu** [comment]
Does by any chance the Mastodon Share add-on offer some pointers on how to add Mastodon to the list of services?

* [Add-on page](https://addons.mozilla.org/en-GB/firefox/addon/mastodon-share/)
* [GitHub repo](https://github.com/kernox/Mastodon-Share)

**Comment by Mte90** [comment]
Actually is not enough because require a settings panel only for mastodon that actually the extension doesn't support.
If I have to implement all this kind of settings for every social network will be a mess actually and a lot of job.

**Comment by stragu** [comment]
So ideally you'd like the Mastodon dev to develop a sharer just like Diaspora has done with share.diasporafoundation.org ?

**Comment by Mte90** [comment]
Yes it will be the best solution, in that way the extension keep to be
simple and light.
Actually for Shaarli i implemented a field where put the url of the custom
hosting of that tool, so there are 2 ways to implement that and depends on
mastodon devs.
