### ISSUE TITLE
Support W3C Micropub standard for publishing to sites and OSS

### ISSUE THREAD

**Issue by tantek** [Mte90/Share-Backported#24]
The recent W3C Micropub standard https://www.w3.org/TR/micropub defines a standard API for clients to interact with servers to publish (and update etc.) status updates, blog posts, and other social information. 

It would be great if the Share Backported add-on supported the Micropub API as a client, so users could use it to share to any Micropub supporting server (of which there are numerous) including open source software:
* WordPress
* Drupal
* Known
* Jekyll

Many more at: https://indieweb.org/Micropub/Servers#CMS_Software

Also step by step test suite at: https://micropub.rocks/

**Comment by Mte90** [comment]
The issues is the same of Mastodon.
Actually the extension use the already available dialog share pages so to implement a support like that for a distributed social like this one is not simple without rethink all the extension and adding a settings page to configure for this kind of socials sharing solution.

**Comment by Mte90** [comment]
Actually that standard doesn't support a modal like the other social networks so I cannot implement not
