### ISSUE TITLE
Messy titles when sharing to diaspora

### ISSUE THREAD

**Issue by RoseTheFlower** [Mte90/Share-Backported#26]
The title contains unnecessary " + " symbols when sharing to diaspora. For instance, for this page the title is "New+Issue+·+Mte90/Share-Backported".

**Comment by Mte90** [comment]
You are the first one to report this issue, in any case I will investigate :-)

**Comment by RoseTheFlower** [comment]
[A screenshot of it](https://share.riseup.net/#vqaHvN9P8GDpzyPppNLPNg).
