### ISSUE TITLE
Shaarli

### ISSUE THREAD

**Issue by techexo** [Mte90/Share-Backported#27]
Hello,
First, thanks a lot for backporting the share function for Firefox Quantum.

I use a webapp allowing the management of bookmarks and notes ([Shaarli](https://github.com/shaarli/Shaarli/)) and the deactivation of the Social API on Firefox Quantum broke its integration (https://github.com/shaarli/Shaarli/issues/1023).

On the Shaarli instance, it seems that the data-service button used to register Shaarli has the following arguments:
```json
data-service
{
    "name":"Shaarli",
    "description":"The personal, minimalist, super-fast, no-database delicious clone.", 
    "author":"Shaarli",
    "version":"1.0.0",
    "iconURL":"https://shaarli_instance_url/tpl/material/images/favicons/favicon-96x96.png",
    "icon32URL":"https://shaarli_instance_url/tpl/material/images/favicons/favicon-32x32.png",
    "icon64URL":"https://shaarli_instance_url/tpl/material/images/favicons/favicon-64x64.png",
    "shareURL":"https://shaarli_instance_url?post=%{url}&amp;title=%{title}&amp;description=%{description}&amp;source=firefoxsocialapi",
    "homepageURL":"https://shaarli_instance_url"
}
```

Do you think it would be possible for your extension to support the adding of customized websites via the king of button used in Shaarli?
I would be more than happy to provide you with an account on my personal Shaarli instance for test purposes if you need so!

Thanks a lot in advance,
Best regards

**Comment by Mte90** [comment]
Actually the extension doesn't implemented that, is the only the modal with services. I didn't know that other services was using the Social API infact as you can see my extension contain more services then before.
So one of the best way is to add share inside the extension itself, I need only the popup url with the parameters for the info and an svg icon for that :-)

**Comment by techexo** [comment]
Hi,
Thanks for your very positive reply!
The issue here is that Shaarli is a software that is often (always?) self-hosted on personal servers, it would thus require in the parameters of the extension the possibility to register a custom URL for the user's Shaarli.

If the URL can be customized in the parameters, it won't be a problem to give the data needed! :)

**Comment by Mte90** [comment]
Uhm like for diaspora I am using a modal with links of different portal or the url to customize.
It will be helpful to have that to avoid of the implementation of specific things for every social.

**Comment by techexo** [comment]
Hi,
Thanks for the quick implementation!
However, there is two issues while sharing:
1) the "url" and "text" arguments in the custom share URL are not replaced while sharing on Shaarli (i.e. my Shaarli try to create a bookmark linking to `http://url` with `text` description). The "title" argument seems to work fine;
2) is it possible for the pop-up share windows to have the vertical scrollbar activated?

Cheers

**Comment by Mte90** [comment]
Uhm seems that I need a Shaarli instance for testing. I will check that issue.
For the vertical actually is not possible, one of the ticket regards the custom size for every modal in the panel

**Comment by Mte90** [comment]
Ok fixed also the vertical, I will release the new version asap :-)

**Comment by techexo** [comment]
Thanks for your work, I will confirm it is fixed once the new version is released :-)

**Comment by Mte90** [comment]
So the modal size of shaarli is enough? Because this will probably the best solution https://github.com/Mte90/Share-Backported/issues/10
