### ISSUE TITLE
Facebook shared image

### ISSUE THREAD

**Issue by popkutt** [Mte90/Share-Backported#28]
It used to pick the correct product main image before for sharing in FB. Now it takes the logo instead of the product image, probably because it is the first image on the page. Example: http://www.nordoutlet.com/et/41965-guess-k%C3%A4ekell.html

**Comment by Mte90** [comment]
I cannot doing anything for that because I am using the share modal of Facebook where I sent the url of the page, so probably is something messing on that site about opengraph.
