### ISSUE TITLE
Add Other Services

### ISSUE THREAD

**Issue by pwd-github** [Mte90/Share-Backported#3]
Namely, Reddit, Tumblr and Telegram.

**Comment by Mte90** [comment]
Good idea!

**Comment by arnaud-jacquemin** [comment]
Diaspora* was available with the old share button : https://activations.cdn.mozilla.net/en-US/diaspora.html
It should be backported too!
It would be great to add Mastodon also.
Thanks in advance !

**Comment by airon90** [comment]
@arnaud-jacquemin Diaspora and distributed social networks need a setting page where to insert the url of the pod you use. It is not so immediate

**Comment by Mte90** [comment]
Actually I implemented tumblr, reddit and telegram :-)
