### ISSUE TITLE
Disabled on every page

### ISSUE THREAD

**Issue by mikeconley** [Mte90/Share-Backported#38]
I'm not sure when this started, but Share Backported is disabled on every page I visit now.

I'm using Firefox Nightly, and the latest build where I can reproduce this is 20171122103138 (Nov 22nd, 2017)

**Comment by mikeconley** [comment]
To be clear, the thing that's disabled is the Page Action in the URL bar. I've noticed that if I customize my toolbars and put the button in the toolbar, everything works from there.

But the Page Action is still disabled everywhere.

**Comment by mikeconley** [comment]
Aaaaand now I realize that for some reason, in the add-on preferences, the Page Action was configured to be disabled. I don't know how that happened, but sorry for the noise!

**Comment by Mte90** [comment]
No worry :-D
