### ISSUE TITLE
Add share icon as a page action

### ISSUE THREAD

**Issue by arnaud-jacquemin** [Mte90/Share-Backported#4]
Hello and thank you for this addon !

Will this button be available as a page action ? Cf. https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/pageAction

I think it would make sense to display the share icon near "bookmark this page" and "email link".

Thanks in advance

**Comment by Mte90** [comment]
It will be more cool indeed :-)

**Comment by Mte90** [comment]
I have to remove that support because is not working but I will continue to work on that!

**Comment by pwd-github** [comment]
I was just coming to create this bug.
