### ISSUE TITLE
Please add Pushover

### ISSUE THREAD

**Issue by HLPJasiri** [Mte90/Share-Backported#41]
Hey there,

good thing I found this addon. Would it be possible to add support for Pushover to send links to (mobile) devices?
https://pushover.net/apps/firefoxshare

Would be greatly appreciated so I can quickly send links to my device(s) again! :)

Thanks for this addon!

**Comment by Mte90** [comment]
If the service has a modal I think that can be possible to integrate it :-)
Do you know if exist a share modal for this service?

**Comment by HLPJasiri** [comment]
Hello!
I'm not sure I understand the requirements correctly, but their API lists different parameters and how to send a message to the device(s): https://pushover.net/api

Hope this helps :)

**Comment by Mte90** [comment]
The API is not the right way, actually this extension use only to open a modal that redirect to another modal of the service made for share links. In that way is very simple to add the support for a service.
So implement this service is over the purpose of this extension, is better to ask to them to do a Firefox extension.
