### ISSUE TITLE
Better alignment of Telegram Icon

### ISSUE THREAD

**Issue by marsjaninzmarsa** [Mte90/Share-Backported#42]
Asymmetrical plane icon looks just ugly, especially as Page Action - feels separated from other icons.

**Comment by Mte90** [comment]
Probably the only solution is edit the svg of the telegram icon. Thanks for the issue!

**Comment by jdittrich** [comment]
It this resolved? It does not look worse than the others imho: 
![grafik](https://user-images.githubusercontent.com/3416487/36949777-3787e0d2-1fed-11e8-99e1-94b578b5b314.png)

**Comment by Mte90** [comment]
No is not yet fixed.
I am not an expert of SVG editing.

**Comment by jdittrich** [comment]
I can try to fix it, the problem is, I don't see what is wrong. Is it that it is round and the others are rectangular? Any other problem I miss to see?

**Comment by Mte90** [comment]
The css code is the same for all the icons so the problem can the google+ icon that is not aligned or the telegram icon looking in this screen.
Maybe we have to check all the image/svg if are aligned rightly.

**Comment by rugk** [comment]
Could you just provide a screenshot and indicate what you think is wrong?

**Comment by Mte90** [comment]
As I can remember if you hover the icons you see a border, with the telegram one is not aligned pretty well.
