### ISSUE TITLE
Share Telegram links in the browser tab

### ISSUE THREAD

**Issue by alexisju** [Mte90/Share-Backported#43]
I use Firefox (Linux) as browser and, when i share a link with Telegram, the plugin do it by the Telegram desktop app. 

I didn't find how to change this in the Firefox settings (it is how Firefox manage tg:// links). 
But maybe it could be possible to have a setting, in Share-Backported, to share links in a  Telegram web tab (https://web.telegram.com), in the browser, and not on the desktop app ?

**Comment by Mte90** [comment]
This is not a fault of the extension but a wrong configuration on your browser.
If I open a tg;// links I got a modal that ask me if use the web or desktop version so you have to check on the configuration of your firefox in the Applications settings and searc for tg.
