### ISSUE TITLE
Resize share popups

### ISSUE THREAD

**Issue by Solidjeuh** [Mte90/Share-Backported#48]
Would it be possible to make the share popup for Facebook a little bigger please? Something like 700 x 600 px ..  

Kind regards,
Andy

![2018-01-19 14 21 55](https://user-images.githubusercontent.com/7800936/35152794-1ed5a92a-fd24-11e7-9268-fd8427c08926.jpg)

**Comment by Mte90** [comment]
As you can see there is already a ticket for that -> https://github.com/Mte90/Share-Backported/issues/10
