### ISSUE TITLE
Modal not open on click on 1.1.0

### ISSUE THREAD

**Issue by jthelwell** [Mte90/Share-Backported#49]
The newest version seems to have broken the add-on.  Clicking on the icon does open the window to choose the service to share to, but clicking on a service does not open the window to share.

**Comment by Mte90** [comment]
Did you tried to go on the settings and click on save?

**Comment by jthelwell** [comment]
That worked!  Thank you.  You might want to add that to the information on
using the add-on.

**Comment by Mte90** [comment]
You are right, I was waiting for other feedback about this problem and trying to understand what is the issue!
