### ISSUE TITLE
Integration with Google Keep

### ISSUE THREAD

**Issue by pbenedict** [Mte90/Share-Backported#50]
One nifty feature of Chrome on my Android is the ability to share web links directly into Google Keep. The note title is the web page title, the note body is just the link. It's a good decent alternative to using the browser's built-in remote bookmark management (ex: Firefox Sync). Can you please consider this integration? Thank you.

**Comment by Mte90** [comment]
I have to see what is the URL for share stuff on Google Keep, so I can evaluate if I can integrate it :-)

**Comment by Ryuno-Ki** [comment]
Um, I [looked around](https://stackoverflow.com/questions/19196238/is-there-a-google-keep-api/19197321#19197321) and found an inofficial client interacting with it:
https://github.com/kiwiz/gkeepapi/blob/cf23ff85c27de6dd085dd932f582ffdaef9c5d68/gkeepapi/__init__.py#L153-L160

Not sure, whether you are eager to play pretend with Google :-)
I'd vote for closing this as Won't Do.

**Comment by Mte90** [comment]
I agree require a SDK so is not suitable for this extension
