### ISSUE TITLE
Share Window Sizes

### ISSUE THREAD

**Issue by codeman6100** [Mte90/Share-Backported#51]
In my experimentation the default size for google+ should be 400x550.  This leaves room for 3 lines of text for a personal message.

**Comment by codeman6100** [comment]
Twitter is fine the way it is.  Facebook should default to 575x700.

**Comment by Mte90** [comment]
Thank you! I will update soon!

**Comment by pwd-github** [comment]
Reddit should be 950*915

**Comment by alexisju** [comment]
but not possible to set windows size of custom shares ?

**Comment by Mte90** [comment]
Do you mean for shaarli?

**Comment by alexisju** [comment]
Indeed

**Comment by Mte90** [comment]
Opened a ticket https://github.com/Mte90/Share-Backported/issues/52

**Comment by alexisju** [comment]
Indeed! :-)
