### ISSUE TITLE
Completely stopped working

### ISSUE THREAD

**Issue by Caspy7** [Mte90/Share-Backported#53]
I can click on the airplane, then select any social media buttons and nothing happens. The buttons all stay there and I can keep clicking them.
I suspect this happened with the 1.1.2 update.

On Windows 10, 64 bit Firefox. Tested in Nightly on my default profile, then fresh profiles in Beta and Release (58).
Tried placing the airplane button under "...", in the address bar, and in the toolbar and got the same result.

Suspect I'm seeing the same as https://addons.mozilla.org/en-US/firefox/addon/share-backported/reviews/1054010/

**Comment by Mte90** [comment]
Can you try if save again your preferences fix the problem?
If yes I will add an alert and check better with that release.

**Comment by Mte90** [comment]
I fixed the bug, it was happening for people not using the settings.
I am releasing right now a new version.
