### ISSUE TITLE
Mastodon is missing the url

### ISSUE THREAD

**Issue by Mte90** [Mte90/Share-Backported#56]
Actually the mastdon implementation has only one parameter insterad the other service 2 for message and url.

We need a way in teh doc to detect when the url is of mastodon and append the url.

**Comment by strk** [comment]
I was unable to make the mastodon share work, is it needed to fix this ticket in order to share at all ? I'm asking beause in the preferences there's a template for the URL to use to post (but I saw no placeholders there)

**Comment by strk** [comment]
NOTE: this addon works for sharing to mastodon: https://github.com/kernox/Mastodon-Share-Browser-Extension

**Comment by Mte90** [comment]
This bug regard the issue that the share modal doesn't include the url shared but only the page title.
The placeholder exist in the settings for mastodon
![screenshot_20180404_121150](https://user-images.githubusercontent.com/403283/38301966-6ade6538-3801-11e8-88b4-0ae03688dffb.png)
