### ISSUE TITLE
The window for FB disappears immediately on opening

### ISSUE THREAD

**Issue by aon1961** [Mte90/Share-Backported#57]
For me, the addon for Facebook does not work. After clicking on the icon for Facebook pops up the window and disappears immediately. I use FF 60.0b13 (64-bit). Disabling uBlock Origin also does not help.

**Comment by aon1961** [comment]
Hello, the window closes before.

**Comment by Mte90** [comment]
Very strange, you are logged to facebook? The window is closed only when the URL change automatically.

**Comment by aon1961** [comment]
Hello, yes I'm loggend in to FB. I think it's related to the new Addon Facebook Container.

**Comment by Mte90** [comment]
I am not using I have to check that behaviour with that addon. Actually this extension doesn't support the containers https://github.com/Mte90/Share-Backported/issues/2

**Comment by Mte90** [comment]
If Facebook container close automatically a tab doesn't matter if it is a window or a tab, I am right about it?
I am not using container in Firefox so to implement it I need help or time to test everything.

**Comment by arrizalamin** [comment]
yeah, it's probably a bug from facebook container, I tried to debug and [this function](https://github.com/mozilla/contain-facebook/blob/4db111746c3ae7b707061b307113dcc09a5d55c8/src/background.js#L207-L216) called twice in popup window and the second call failed to create new tab while in normal window it's called only once. I'll try to send a PR.

**Comment by Mte90** [comment]
Fixed by pr

**Comment by aon1961** [comment]
Hello,

Thx for anserwing.
For me FB window is not opened as a new window special than a new tab. After confirming the post, the tab will not close. The FB-Posting has been entered correctly.

Greetings from Germany 😊
--
Rainer Noa

Wilhelmstr. 7
66482 Zweibrücken

Fon:      +49 (0) 6332 86 51 06
Mobil:  +49 (0) 171 742 18 56
E-Mail: rainer.noa@outlook.com<mailto:Rainer.Noa@outlook.com>
________________________________
Von: Daniele Scasciafratte <notifications@github.com>
Gesendet: Montag, 23. April 2018 11:09
An: Mte90/Share-Backported
Cc: Rainer Noa; Author
Betreff: Re: [Mte90/Share-Backported] The window for FB disappears immediately on opening (#57)


Closed #57<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMte90%2FShare-Backported%2Fissues%2F57&data=02%7C01%7C%7Cd5bb94d073c24f3e4a3c08d5a8f9dd56%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636600713460168262&sdata=Qrkw9Csy9PH5K6L9C34zhUWRHzxJqSRav88N8DNhP9g%3D&reserved=0>.
