### ISSUE TITLE
Add support to Share to Skype

### ISSUE THREAD

**Issue by miguedevel** [Mte90/Share-Backported#58]
Pretty much similar to the functionality of Chrome's Skype extension.

**Comment by Mte90** [comment]
I don't know this extension, this one works with modal windows with a specific url where I can set the url and the text.
If you can give to me the link of this extension I can try to study and see how works.

**Comment by miguedevel** [comment]
Here it is. Whenever I want to share the link to my current tab to a Skype contact, I just click the Skype toolbar icon, then it opens a list of contacts to select and send. https://chrome.google.com/webstore/detail/skype/lifbcibllhkdhoafpjfnlhfpfgnpldfl

**Comment by miguedevel** [comment]
Hopefully you'll read this even if the issue is closed but I think it's as simple as invoking this url: https://web.skype.com/share?url=

For example to share to Skype this very website opening a tab to https://web.skype.com/share?url=https%3A%2F%2Fgithub.com%2FMte90%2FShare-Backported%2Fissues%2F58 does the trick.

**Comment by Mte90** [comment]
Perfect, this is what I need to add the support!
