### ISSUE TITLE
Explain why extension needs permission to "Monitor extension usage and manage themes"

### ISSUE THREAD

**Issue by hackel** [Mte90/Share-Backported#61]
Just got prompted to authorize the extension to "Monitor extension usage and manage themes."  Why?  Neither of these things seem like something a simple URL sharing extension needs to do.  While I think Firefox is just giving a terrible description for the management API, I still wonder what it is being used for, and other semi-conscious users likely will as well.  Thanks.

**Comment by Mte90** [comment]
Probably the new permission added on https://github.com/Mte90/Share-Backported/blob/master/manifest.json#L53 are showing this message.
Actually the extension doesn't use themes so maybe is something on Firefox side.
In any case we added the support for the Cointaner feature on 1.2.0, can I have a screenshot about the message?
DO you have any hints about where to show this information? I am not sure about what is the best place for that.
Also what Firefox version are you using?

A point that the code is open source and I want that the feature seems transparent and privacy conscious so thanks for the report.

**Comment by ryanho** [comment]
![screenshot_20180424_215434](https://user-images.githubusercontent.com/204075/39191905-855721f2-480a-11e8-8d30-b3d5e65067e3.png)
Firefox 60.0b12

**Comment by Mte90** [comment]
I don't understand chinese ( I guess) so I tried in another firefox profile in a language that I can understand (XD) and seems that you guys are right.
For the actual permission asked Firefox is alerting about Monitoring use of extension and manage themes.

In our case we need only the first case, monitor the extension in stalled to add the support for Container. I will ask to firefox theme in case if it is possible to improve this alert.

**Comment by hackel** [comment]
I would add that information to the release notes on AMO.  Unfortunately, you can only view this from within Firefox *after* you have approved the new permission and installed the update.  At least if some annoying person like me gets curious, they can find it on the website!

**Comment by Mte90** [comment]
You are right about the notes, I was uploading only in the field for the reviewer and not for the public for an year -.-'

I written all the changelog there https://github.com/Mte90/Share-Backported/releases and added on the changelog on AMO for 1.2.0 for the future this will not happen anymore.

About the alert is that Firefox check only the permission and not what API I am using really so the `management` API that we use to detect container can be used also for themes.
