### ISSUE TITLE
options issue

### ISSUE THREAD

**Issue by difool2nice** [Mte90/Share-Backported#62]
1.2.0 : i can't save prefs, it can share normally but can't hide share chosen links as expected
Firefox 59.0.2 x64 - windows 10 x64

**Comment by Mte90** [comment]
Can you try with the latest version?

**Comment by difool2nice** [comment]
sorry but i have fixed the issue ! there was something wrong in the Custom Shares section in which i added a wrong link so it refused to save my prefs ! that was my mistake ! now it's working fine !
Great handy & useful addon, it's a must have for me, in the first line of the webext to install. keep up the good work

**Comment by Mte90** [comment]
Thanks!
