### ISSUE TITLE
There's no button to share to weibo 没有分享到微博

### ISSUE THREAD

**Issue by Goaline** [Mte90/Share-Backported#63]
There's no button to share to weibo 没有分享到微博

**Comment by Mte90** [comment]
I didn't know of this service (seems mainly asian) but seems that I found the url to share the url.

`http://service.weibo.com/staticjs/weiboshare.html?url=<raw-encoded-url>&title=<raw-encoded-title>`

Looking online for me is not clear if weibo is something that can be installed on custom hosts, can you confirm that?

**Comment by irvin** [comment]
use the following link, you can have another param for images url (if available)

`http://service.weibo.com/share/share.php?url=<raw-encoded-url>&title=<raw-encoded-title>&pic=<link-to-pic-if-available>`
