### ISSUE TITLE
Bug with Pinboard

### ISSUE THREAD

**Issue by stephenjudge** [Mte90/Share-Backported#64]
When using the Pinboard button either from the Share-Backported button or from the address bar icon, the page Title and URL are not being populated in the correct fields of the Pinboard save dialogue.

I made a quick screencast showing the resulting action from using Share-Backported and from using [another Pinboard extension](https://addons.mozilla.org/en-GB/firefox/addon/pinboard-webextension/). In the other Pinboard extension the Title, URL and selected text are populated in the correct Pinboard save dialogue window.

https://youtu.be/ms0ZaaChQbA

It would be great if you could fix this, then I wouldn't have a need for the other Pinboard extension. I'm sure you're aware but the Pinboard API documentation is [here](https://pinboard.in/api/).

**Comment by Mte90** [comment]
I will look asap to see if https://github.com/Mte90/Share-Backported/blob/master/modal/modal.html#L57 the parameters I am using are the right one.

**Comment by Mte90** [comment]
There was a typo in the url of pinboard -.-' fixed :-)
a new release will available asap

**Comment by stephenjudge** [comment]
Thanks for working on this fix, however it is still not quit right. The webpage title is being inserted into the Description field rather than the appropriate title field. 

![Screenshot](http://imgur.com/lAWQ0Yil.png)

**Comment by Mte90** [comment]
Probably I have to switch description with title and the issue will be fixed.

**Comment by stephenjudge** [comment]
Great job thanks.
