### ISSUE TITLE
Pop Window after sharing not closing automaticcally in Firefox 60.0.2

### ISSUE THREAD

**Issue by lahtag** [Mte90/Share-Backported#65]
Excellent Add-on replacing the existing one of Firefox.

While Updating Firefox to 60.0.2, the window open after sharing is not closing automatically anymore like before.
Is there any help to resolve this.
Thank you

**Comment by lahtag** [comment]
Dear Sir,

Thank you so much for the fast response.

As you mentioned " ...twitter, Facebook and google plus ...) within you
response I went back and checked one by one.
All others are closing after share except for Facebook.

I attached the scan for information how the windows is coming.

Thank once again for your fast response

**Comment by Mte90** [comment]
Perfect I will check ASAP :-)

**Comment by lahtag** [comment]
Thank you so much. Excellent Job.

All The Best!
