### ISSUE TITLE
Use the selected text as title for the share

### ISSUE THREAD

**Issue by Mte90** [Mte90/Share-Backported#70]
Can be cool if you want to share an url to use as title the text htat is selected in the page itself.

**Comment by islamnurdin** [comment]
On it

**Comment by islamnurdin** [comment]
Could you please share source where I can make change?

**Comment by Mte90** [comment]
Well this can be complicated if you don't know how works the browser extension messaging system.
You need to change https://github.com/Mte90/Share-Backported/blob/master/modal/modal.js that file in a way that can access the tab where is the page and probably inject a content script to get the selected text and send with messaging to that file.
I am not sure if there is a browser api that enable by tab id to get the selected text.

**Comment by Mte90** [comment]
It is enough to follow this https://stackoverflow.com/a/34181338/1902215 to add this support and change the code in https://github.com/Mte90/Share-Backported/blob/master/modal/modal.js#L250 to execute that code.
