### ISSUE TITLE
Adding new sharing services

### ISSUE THREAD

**Issue by AlainCo** [Mte90/Share-Backported#74]
Hi,
I'm new orphan of a sharing extension.
Thanks for Share-Backported.

Classic sharing seems perfect, but I was using custom sharing actions
It seems the only extensions are for Mastodon and  Shaarli...

is it possible to implement unlimited custom links, 
or why not the one I propose below:

Scoop.it
https://www.scoop.it/bookmarklet?url=${link}

Google Translate [EN]
https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=${link}

Feedly subscribe
http://feedly.com/i/subscription/feed/${link}

Feedly add content
https://feedly.com/i/discover/sources/search/feed/${link}

Twitter Search URL
https://twitter.com/search?f=tweets&vertical=default&src=typd&q=${link}

Sorry, I cannot help since I don't know firefox.

**Comment by Mte90** [comment]
ShareBackported right now don't support custom services but I think that we can integrate this services.

**Comment by Sav22999** [comment]
Adding also Pinterest, Instagram, Instapaper, Evernote

**Comment by Mte90** [comment]
So of this ticket is missing Feedly and Twitter search (I don't know if we can find a logo for it)

**Comment by Mte90** [comment]
I opened #107 so I can close this one
