### ISSUE TITLE
Shaarli not working anymore (my.framasoft.org)

### ISSUE THREAD

**Issue by alexgarel** [Mte90/Share-Backported#75]
Hello, this extension use to work well with Shaarli, and I use it with https://my.framasoft.org/ but it stopped working in a quite strange way : the login page is ok, then I see the form to add my url and it seems to work, but as I submit it I got a 404 Not Found. 

If I use an extension like https://github.com/ikipatang/shaarli-web-extension it works fine.

**Comment by alexgarel** [comment]
Oh and first thanks for the extension provide me with good services for more than one year :-)

**Comment by Mte90** [comment]
Maybe shaarli changed his urls for sharing.
Are you sure about the url you put on 
![Screenshot_20190325_132727](https://user-images.githubusercontent.com/403283/54919688-c169aa80-4f01-11e9-9db3-d5f99711af11.png)

**Comment by alexgarel** [comment]
Quite sure yes, as I use the same for shaarli-web-extension and compared with online form.
What is strange is that I tried to get the traffic in the popup windows using web developper panel, and I was unable to get it.

**Comment by alexgarel** [comment]
Oups for network in developper panel it was because I had XHR filter activated :blush: 

So I tracked down the problem. It seems that my instance does not accept to use unescaped parameters  like if I bookmark this page, I will have `?post=http://github.com/Mte…` instead of `?post=https%3A%2F%2Fgithub.com%2FMte…`

(maybe it is due to a proxy configuration at https://my.framasoft.org/

**Comment by Mte90** [comment]
New version released, wait few hours before check in your browser fora new release with this fix :-)

**Comment by alexgarel** [comment]
Great, thanks a lot !
