### ISSUE TITLE
Whatsapp support

### ISSUE THREAD

**Issue by Mte90** [Mte90/Share-Backported#79]

**Comment by Pierre771** [comment]
Thanks for adding the request for adding Whatsapp

**Comment by Pierre771** [comment]
Thanks for Whataspp !

**Comment by Pierre771** [comment]
A little detail remark : you suiggest the installation of Whatsaqpp soft (.exe). In Windows 10, the appli Whatsapp Desktop is more modern

**Comment by Mte90** [comment]
I don't suggest to install any app of whatsapp.
I am using a link internal to whatsapp but I don't know whats happen when using that on windows.
