### ISSUE TITLE
Custom Email System

### ISSUE THREAD

**Issue by ligneca** [Mte90/Share-Backported#80]
I run my own email server with it's own webmail client.  If you provided one "custom" field I could paste in the URL for composing a new message and it would work with any email system, not just those you have provided.  Thank you for such a great add-on.

**Comment by ligneca** [comment]
Whoops!  I just figured out if I put it under Shaarli, whatever that is, it works.  Thanks for implementing that. Best, Brian

**Comment by Mte90** [comment]
Well this is not the right purpose of that field but nice workaround 😂
