### ISSUE TITLE
Blocking sharing of "about:" url in Button modal

### ISSUE THREAD

**Issue by Sav22999** [Mte90/Share-Backported#82]
If you are in a tab, where its URL is "about:" (e.g. config, addons, preferences, ect) it should block the sharing, because the most of services returns an error.

Some examples (screens):
![immagine](https://user-images.githubusercontent.com/32335378/66444683-77cb5200-ea44-11e9-9790-755203fa7c4d.png)
![immagine](https://user-images.githubusercontent.com/32335378/66444702-8580d780-ea44-11e9-87c9-664c0dd91490.png)

**Comment by Mte90** [comment]
We need to show an alert in the modal view for those cases

**Comment by RajkumarMittal** [comment]
hey can i contribute in this? i can make this better

**Comment by Mte90** [comment]
yes no problem :-)

**Comment by RajkumarMittal** [comment]
ok thanks

**Comment by Mte90** [comment]
pageaction aslready support it but not the button https://github.com/Mte90/Share-Backported/blob/a20819b822b2504bcaa72c035dac4fa1389dcc39/background.js#L45

**Comment by Ryuno-Ki** [comment]
I wonder, whether we could use [String.prototype.startsWith](https://caniuse.com/#feat=mdn-javascript_builtins_string_startswith) in these cases while we are at it …

**Comment by Mte90** [comment]
For our needs are equivalent, the point is for the browser action that we need to implement a code to show the button
