### ISSUE TITLE
Update GUI to modern style

### ISSUE THREAD

**Issue by Sav22999** [Mte90/Share-Backported#83]
The GUI is very old, I think it would look better in a new modern style.
I mean the button effect -> now it is "3D effect"

**Comment by Mte90** [comment]
It is based on the original Share feature design from firefox, we can align probably with the actual one indeed

**Comment by Sav22999** [comment]
Exactly, with "quantum style" and, if it's possible, add dark theme too 😄

**Comment by Sav22999** [comment]
I'm working on it, also to modernised "Options"
