### ISSUE TITLE
Add the option to change the order of services

### ISSUE THREAD

**Issue by Sav22999** [Mte90/Share-Backported#86]
It would be a very nice thing can change the sort/order of services.

**Comment by Ryuno-Ki** [comment]
How would you imagine the UX here?
Is the extension also available on mobile?

**Comment by Sav22999** [comment]
Maybe in the option section, just changing number (in a textbox)

**Comment by Ryuno-Ki** [comment]
Okay, that would be https://github.com/Mte90/Share-Backported/blob/28d43921f89841473c9cbcaba78bc4d841320fc2/options/options.html then (labelled „Preferences” in the detail view of the addon in `about:addons` for me).

@Mte90 Would you be willing to accept PRs for this?

**Comment by Mte90** [comment]
Yes of course @Ryuno-Ki

**Comment by Ryuno-Ki** [comment]
Working on it in #94.

**Comment by Ryuno-Ki** [comment]
I haven't worked much with Web Extensions yet, so … just to be sure:
https://github.com/Mte90/Share-Backported/blob/994c2dacf2c34c01e33e2579c2aaab3e600fb453/modal/modal.js#L92
is reading the information stored with https://github.com/Mte90/Share-Backported/blob/994c2dacf2c34c01e33e2579c2aaab3e600fb453/options/options.js#L15

If so, I'd find the priorities there also and could update the modal.
@Sav22999 You can already test the latest version as [temporary addon](https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/) in Firefox and provide feedback, whether it matches your imagination.

@Mte90 I will look into the modal another day (tomorrow perhaps).

**Comment by Sav22999** [comment]
@Ryuno-Ki it's is exactly what a want to!
In my case, anyway, it doesn't work ... I mean, in the option it works correctly, but it doesn't show icon in that order

**Comment by Ryuno-Ki** [comment]
I know. That's the missing piece and reason for my question above.

But good to know, that the preference page can stay like this for now!

**Comment by Sav22999** [comment]
Just an advice, maybe ... separate textbox (reduce width) because it's so crowded

![immagine](https://user-images.githubusercontent.com/32335378/66983582-257bd800-f0b9-11e9-93f0-370811e07fcf.png)

**Comment by Mte90** [comment]
Yes you was right, that was the method to read the options saved, now the FF devtools in firefox nightly support the storage tabs so you can inspect those values :-)

**Comment by Mte90** [comment]
@Ryuno-Ki don't forget to add yourself to the contributor list in the readme :-)

**Comment by Ryuno-Ki** [comment]
Too much fame :-D

Ah, it explains why I couldn't find it in localStorage m(

**Comment by Sav22999** [comment]
@Ryuno-Ki so, is it possible to do?

**Comment by Ryuno-Ki** [comment]
I believe, #104 should fix this ticket.

**Comment by Sav22999** [comment]
👍  oh, sorry, I didn't see.

**Comment by Ryuno-Ki** [comment]
No, I just finished it. No worries, you can't see edits on my local machine (I hope).
For the general public to consume the changes, @Mte90 would need to make a new release to [AMO](https://addons.mozilla.org), I guess.

But I'd be pleased if you could try the modifications once the PR was merged, @Sav22999.

**Comment by Sav22999** [comment]
I've just checked (debug mode) and YES! That's absolutely amazing! Finally I can choose my services order. Thank you very much!
