### ISSUE TITLE
ActionPage shortcut always black ...

### ISSUE THREAD

**Issue by Sav22999** [Mte90/Share-Backported#90]
The main icon of extension works correctly, so it changes based on theme color.
Instead, ActionPage icon remains always black, and if you have Dark Theme it is almost hidden

![immagine](https://user-images.githubusercontent.com/32335378/66483290-14254100-eaa5-11e9-8f59-78c33b46f824.png)

**Comment by Mte90** [comment]
Duplicate for https://github.com/Mte90/Share-Backported/issues/15
