### ISSUE TITLE
Options section height bug

### ISSUE THREAD

**Issue by Sav22999** [Mte90/Share-Backported#91]
In the options section, the height of the panel continues to increase indefinitely (you can see that if you go to the end of that section)

Screen1:
![immagine](https://user-images.githubusercontent.com/32335378/66559918-8dc93780-eb56-11e9-9bf2-bf7455280795.png)

Screen2:
![immagine](https://user-images.githubusercontent.com/32335378/66559955-a46f8e80-eb56-11e9-942a-e08451308937.png)

Screen3:
![immagine](https://user-images.githubusercontent.com/32335378/66559979-b4876e00-eb56-11e9-8fca-cbaefe0792e7.png)

**Comment by Sav22999** [comment]
@Hobbesball Probably you have an older version than mine, which is "69.0.2 (64 bit)" (on Windows 10 Pro)

**Comment by Hobbesball** [comment]
after updating I am able to reproduce the issue. I'll be working on fixing it.

**Comment by Mte90** [comment]
Seems that @Sav22999 already did the patch https://github.com/Mte90/Share-Backported/pull/92 but on the wrong master with conflicts

**Comment by Sav22999** [comment]
@Mte90 Nope, I didn't fixed this bug, I've fixed #73 bug 😅

**Comment by Mte90** [comment]
Ops my fault, @Hobbesball you can work on that :-)

**Comment by Sav22999** [comment]
Nobody worked to this bug, so I fixed today 😄
