### ISSUE TITLE
Inform on first Whatsapp usage on Windows

### ISSUE THREAD

**Issue by Mte90** [Mte90/Share-Backported#93]
Right now when is used the whatsapp share on windows there will be opened a page to download the client and people report that as an error of the extension.

We need to add an alert on first usage to avoid this confusion.

**Comment by Muskan284** [comment]
hey , i would like to work on it

**Comment by Muskan284** [comment]
can u describe when that alert should appear or what should be the content of alert

**Comment by Mte90** [comment]
I think something like "On windows is required to use the client so the next window will ask to download it from the whatsapp server automatically".
And appear on the first click on the modal share window.

**Comment by Mte90** [comment]
This is difficult because we cannot detect if the client is installed.
So I will close it
